import type { PythonTip } from "./python-tip-types";

/** Patterns found across 1,300+ strategy code samples (QuantConnect + pandas). */
export const PYTHON_TIPS_EXTRA: PythonTip[] = [
  {
    syntax: "AlgoLib",
    pattern: /\bAlgoLib\b/,
    en: "AlgoLib is a helper library used in many Quant Buffet templates. It wraps common QuantConnect chores—universe setup, scheduling, or signal tables—so the main algorithm file stays shorter and closer to the published paper’s steps.",
    zh: "AlgoLib 是本站策略模板常用的辅助库，封装了宇宙选股、定时任务或信号表等重复工作，使主算法文件更短、更贴近论文步骤。",
    className: "qb-py-tip-algolib",
  },
  {
    syntax: "Slice (data)",
    pattern: /\bSlice\b/,
    en: "Slice is the data packet OnData receives. It holds the latest bars or ticks for each subscribed symbol. You check slice.ContainsKey(symbol) before reading prices so you do not trade on missing data.",
    zh: "Slice 是 OnData 收到的数据包，包含各订阅标的的最新 K 线或 tick。交易前常用 slice.ContainsKey 确认该标的有数据，避免空读。",
    className: "qb-py-tip-slice",
  },
  {
    syntax: "data.Bars / data[symbol]",
    pattern: /\bdata\.(?:Bars|Symbol)\b/,
    en: "In OnData, data gives access to the current bar for a symbol—open, high, low, close, and volume. Strategies compare today’s bar to history or to other stocks in the same slice.",
    zh: "OnData 中的 data 可读取某标的当前 K 线的开高低收和成交量，用于与历史或其他股票比较。",
    className: "qb-py-tip-databars",
  },
  {
    syntax: ".Current.Value",
    pattern: /\.Current\.Value\b/,
    en: "Indicators expose .Current.Value as their latest reading—e.g. 50-day average price or RSI level. Check .IsReady first so you do not trade before the indicator has enough history.",
    zh: "指标用 .Current.Value 表示最新数值（如 50 日均线、RSI）。应先确认 .IsReady，避免历史不足时误用。",
    className: "qb-py-tip-current",
  },
  {
    syntax: ".IsReady",
    pattern: /\.IsReady\b/,
    en: "IsReady becomes true once an indicator has collected enough past bars. Trading before that can use distorted values (e.g. a 200-day average on day 5). Most rules wrap signals with if indicator.IsReady.",
    zh: "IsReady 在指标积累足够历史后为真。过早交易会得到失真读数（如第 5 天就算 200 日均线）。信号通常包在 if indicator.IsReady 里。",
    className: "qb-py-tip-ready",
  },
  {
    syntax: "def OnSecuritiesChanged",
    pattern: /\bdef\s+OnSecuritiesChanged\s*\(/,
    en: "Called when the universe adds or removes stocks. Use it to create per-symbol indicators, warm them up, or clean state so delisted names do not leave ghost positions in your logic.",
    zh: "当股票池增减标的时触发。用于为每只新股票创建指标、预热，或清理已剔除标的的状态，避免“幽灵”持仓逻辑。",
    className: "qb-py-tip-securities-changed",
  },
  {
    syntax: "Universe.Unchanged",
    pattern: /\bUniverse\.Unchanged\b/,
    en: "Return this from a universe filter when you want to keep yesterday’s list unchanged—saves work on days with no rebalance and avoids unnecessary indicator resets.",
    zh: "宇宙筛选函数返回 Unchanged 表示维持昨日名单不变，在非调仓日省算力并避免指标被无谓重置。",
    className: "qb-py-tip-unchanged",
  },
  {
    syntax: "self.UniverseSettings",
    pattern: /\bself\.UniverseSettings\b/,
    en: "UniverseSettings controls how coarse/fine selection behaves—resolution, fill-forward, minimum time in universe, etc. Tune it so your backtest matches the paper’s holding rules and liquidity assumptions.",
    zh: "UniverseSettings 配置粗/细筛选行为（分辨率、填充、最短停留等），用于让回测符合论文的持仓与流动性假设。",
    className: "qb-py-tip-universe-settings",
  },
  {
    syntax: "self.AddData(…)",
    pattern: /\bself\.AddData\s*\(/,
    en: "AddData subscribes to custom datasets—economic releases, alternative data, or CSV-style feeds not built into standard equity quotes. The data class defines how each row is parsed.",
    zh: "AddData 订阅自定义数据（宏观发布、另类数据或类 CSV  feed），由数据类定义每行如何解析。",
    className: "qb-py-tip-adddata",
  },
  {
    syntax: "PythonData / CustomData",
    pattern: /\b(?:PythonData|CustomData)\b/,
    en: "Base types for custom data streams. You subclass them to map columns (date, value, symbol) so QuantConnect can align external series with market bars in OnData.",
    zh: "自定义数据流的基类。通过子类映射日期、数值、代码等字段，使外部序列与行情在 OnData 中对齐。",
    className: "qb-py-tip-customdata",
  },
  {
    syntax: "def CoarseSelectionFunction",
    pattern: /\bdef\s+CoarseSelectionFunction\b/,
    en: "First pass of a two-stage stock screen—typically price, volume, and dollar volume filters across the whole market. It shrinks thousands of names to a liquid candidate set cheaply.",
    zh: "两阶段选股的第一遍：通常按价格、成交量、成交额在全市场粗筛，把数千只股票缩小到流动性合格的候选集。",
    className: "qb-py-tip-coarse",
  },
  {
    syntax: "def FineSelectionFunction",
    pattern: /\bdef\s+FineSelectionFunction\b/,
    en: "Second pass that receives fundamental fields (P/E, sectors, etc.) for coarse winners. Here you rank or filter by accounting ratios before the portfolio is formed.",
    zh: "第二遍对粗筛结果读取基本面（市盈率、行业等），再按财务比率排序或过滤，形成最终组合。",
    className: "qb-py-tip-fine",
  },
  {
    syntax: "self.IsWarmingUp",
    pattern: /\bself\.IsWarmingUp\b/,
    en: "True during the warmup period before the official backtest start. Skip placing trades while IsWarmingUp so indicators and rolling stats are fully seeded.",
    zh: "在正式回测开始前的预热期为真。此期间应跳过下单，让指标与滚动统计充分初始化。",
    className: "qb-py-tip-warming-flag",
  },
  {
    syntax: "self.Log(…) / Debug",
    pattern: /\bself\.(?:Log|Debug)\s*\(/,
    en: "Log and Debug write messages to the backtest log—useful to trace rebalance dates, position counts, or signal values when a result looks wrong. They do not affect performance numbers.",
    zh: "Log 与 Debug 把信息写入回测日志，便于追踪调仓日、持仓数或信号值；不影响绩效数字本身。",
    className: "qb-py-tip-log",
  },
  {
    syntax: "self.Plot(…)",
    pattern: /\bself\.Plot\s*\(/,
    en: "Plot draws custom charts in QuantConnect reports—e.g. spread between two signals or portfolio leverage over time. Helps visually sanity-check logic beyond raw returns.",
    zh: "Plot 在 QC 报告中绘制自定义曲线（如两信号之差、杠杆变化），便于用图形检查逻辑是否合理。",
    className: "qb-py-tip-plot",
  },
  {
    syntax: "self.Transactions",
    pattern: /\bself\.Transactions\b/,
    en: "Transactions records orders the algorithm sent—fills, cancellations, and fees. Inspect it for turnover analysis or to confirm rebalance days match the paper.",
    zh: "Transactions 记录算法发出的订单、成交与费用，可用于分析换手率或核对调仓日是否与论文一致。",
    className: "qb-py-tip-transactions",
  },
  {
    syntax: "OrderStatus / OrderTicket",
    pattern: /\b(?:OrderStatus|OrderTicket)\b/,
    en: "Order objects describe live order state—submitted, filled, or canceled. OnOrderEvent handlers use these to chain stops, record slippage, or block duplicate entries.",
    zh: "订单对象描述提交、成交或取消等状态。OnOrderEvent 中可据此串联止损、记录滑点或防止重复下单。",
    className: "qb-py-tip-orderobj",
  },
  {
    syntax: "self.SetSecurityInitializer",
    pattern: /\bself\.SetSecurityInitializer\s*\(/,
    en: "Runs setup code whenever a new security enters the universe—often to set leverage, fee models, or slippage per asset class before any orders fire.",
    zh: "新标的进入宇宙时执行初始化，常用于设置杠杆、费用或滑点模型，再允许后续下单。",
    className: "qb-py-tip-init-security",
  },
  {
    syntax: "DataNormalizationMode",
    pattern: /\bDataNormalizationMode\b/,
    en: "Controls how prices are adjusted for splits and dividends—raw, adjusted, or total return. Wrong mode can fake momentum or distort long-horizon backtests.",
    zh: "控制价格是否按拆股、分红调整。模式选错会制造虚假动量或扭曲长期回测。",
    className: "qb-py-tip-norm",
  },
  {
    syntax: "SubscriptionDataConfig",
    pattern: /\bSubscriptionDataConfig\b/,
    en: "Fine-grained subscription settings—fill-forward, extended hours, mapping mode—for a symbol. Advanced strategies tune this when mirroring vendor data conventions.",
    zh: "某标的的精细订阅配置（向前填充、延长交易时段、映射模式等），在复现数据商惯例时使用。",
    className: "qb-py-tip-subcfg",
  },
  {
    syntax: "self.AddOption(…)",
    pattern: /\bself\.AddOption\s*\(/,
    en: "Adds listed options on an underlying equity. Option strategies read chains, greeks, or implied vol surfaces—much heavier data than stocks alone.",
    zh: "添加股票对应的期权链。期权策略读取合约、greek 或隐含波动率，数据量远大于单纯股票。",
    className: "qb-py-tip-option",
  },
  {
    syntax: "OptionRight / OptionChain",
    pattern: /\b(?:OptionRight|OptionChain)\b/,
    en: "OptionRight is call vs put; OptionChain lists strikes and expiries available at a moment. Used for covered calls, spreads, or volatility timing papers.",
    zh: "OptionRight 区分认购/认沽；OptionChain 列出当时可用执行价与到期日，用于备兑、价差或波动率类策略。",
    className: "qb-py-tip-optionchain",
  },
  {
    syntax: "self.AddIndex(…)",
    pattern: /\bself\.AddIndex\s*\(/,
    en: "Subscribes to an index level (e.g. SPX) as a signal or benchmark without trading every constituent. Useful for macro filters or index-option underlyings.",
    zh: "订阅指数点位（如 SPX）作信号或基准，无需交易全部成分股，常用于宏观过滤或指数期权标的。",
    className: "qb-py-tip-index",
  },
  {
    syntax: "TradeBar / QuoteBar",
    pattern: /\b(?:TradeBar|QuoteBar)\b/,
    en: "TradeBar is OHLCV trade data; QuoteBar adds bid/ask for microstructure or spread strategies. You pick the type matching your data subscription resolution.",
    zh: "TradeBar 为成交 OHLCV；QuoteBar 含买卖价，适合微观结构或价差策略。类型需与订阅的数据一致。",
    className: "qb-py-tip-bar",
  },
  {
    syntax: "Market.USA / Market.",
    pattern: /\bMarket\.\w+/,
    en: "Market identifies which exchange or region a symbol belongs to—USA, EUR, etc.—so the engine routes corporate actions, hours, and currency correctly.",
    zh: "Market 标明交易所或地区（USA、EUR 等），引擎据此处理公司行动、交易时段与货币。",
    className: "qb-py-tip-market",
  },
  {
    syntax: "BrokerageName",
    pattern: /\bBrokerageName\b/,
    en: "Selects a named brokerage profile (Interactive Brokers, Oanda, etc.) with realistic margin and order types for that venue when paired with SetBrokerageModel.",
    zh: "选择具名经纪商配置（IB、Oanda 等），与 SetBrokerageModel 配合模拟该平台的保证金与订单类型。",
    className: "qb-py-tip-brokername",
  },
  {
    syntax: "RateOfChange / ROC",
    pattern: /\bRateOfChange\s*\(/,
    en: "RateOfChange measures percent change over N bars—classic momentum input. Compare across many stocks at once for cross-sectional rank strategies.",
    zh: "RateOfChange 计算 N 根 K 线的百分比变化，是经典动量输入，可用于截面排名策略。",
    className: "qb-py-tip-roc",
  },
  {
    syntax: "StandardDeviation / ATR",
    pattern: /\b(?:StandardDeviation|AverageTrueRange)\s*\(/,
    en: "Volatility tools: StandardDeviation of returns or Average True Range of prices. Used for risk parity sizing, stop widths, or filtering chaotic names.",
    zh: "波动率工具：收益标准差或平均真实波幅 ATR，用于风险平价仓位、止损宽度或过滤波动过大标的。",
    className: "qb-py-tip-vol",
  },
  {
    syntax: "DataFrame",
    pattern: /\bDataFrame\b/,
    en: "A pandas table—rows are dates or symbols, columns are fields. Strategies bulk-compute signals on the whole matrix instead of looping bar-by-bar in Python.",
    zh: "pandas 表格：行多为日期或股票，列为字段。可对整个矩阵批量算信号，而非逐根 K 线循环。",
    className: "qb-py-tip-df",
  },
  {
    syntax: "Series",
    pattern: /\bSeries\b/,
    en: "A single column of data indexed by time or symbol. Many indicators and signal pipelines are stored as Series before merging into a DataFrame.",
    zh: "单列数据，以时间或股票为索引。许多指标与信号先存为 Series 再并入 DataFrame。",
    className: "qb-py-tip-series",
  },
  {
    syntax: ".loc[ ]",
    pattern: /\.loc\s*\[/,
    en: "pandas label-based indexing—pick rows by date and columns by name. Common for aligning factor values on rebalance day without off-by-one errors.",
    zh: "pandas 按标签索引，用日期选行、用列名选字段，便于在调仓日对齐因子值。",
    className: "qb-py-tip-loc",
  },
  {
    syntax: ".iloc[ ]",
    pattern: /\.iloc\s*\[/,
    en: "Position-based indexing (0, 1, 2…) when you care about “last row” rather than calendar date—handy for quick prototypes, but easier to misalign than .loc.",
    zh: "按位置索引（0、1、2…），适合取“最后一行”等不依赖日历的场景，但比 .loc 更易对错行。",
    className: "qb-py-tip-iloc",
  },
  {
    syntax: ".groupby( )",
    pattern: /\.groupby\s*\(/,
    en: "Splits a table into groups—by industry, country, or quintile—then applies a function to each group. Standard for portfolio-neutral factor scores.",
    zh: "按行业、国家或分位分组再分别计算，是组合中性化因子分数的常用写法。",
    className: "qb-py-tip-groupby",
  },
  {
    syntax: ".pct_change( )",
    pattern: /\.pct_change\s*\(/,
    en: "Turns price levels into period returns (percent change). Feeds momentum, mean-reversion, and volatility estimators in one vectorized step.",
    zh: "把价格变为区间收益率（百分比变化），一步生成动量、均值回归或波动率估计的输入。",
    className: "qb-py-tip-pct",
  },
  {
    syntax: ".rolling( )",
    pattern: /\.rolling\s*\(/,
    en: "Rolling window calculations on a Series—moving average, rolling sum, or rolling std—without manual loops. Window size defines lookback length.",
    zh: "在 Series 上做滚动窗口运算（均线、滚动和、滚动标准差等），窗口长度即回望期。",
    className: "qb-py-tip-rolling",
  },
  {
    syntax: ".shift( )",
    pattern: /\.shift\s*\(/,
    en: "Moves data down a row to lag it—yesterday’s signal, prior month’s return. Essential to avoid lookahead bias when using past values.",
    zh: "将数据下移一行实现滞后（昨日信号、上月收益），用历史值时必须配合以免前视偏差。",
    className: "qb-py-tip-shift",
  },
  {
    syntax: "zip( )",
    pattern: /\bzip\s*\(/,
    en: "Walks several lists in parallel—e.g. symbols with weights—when placing many orders in one rebalance loop without pandas merge overhead.",
    zh: "并行遍历多个列表（如代码与权重），在调仓循环中同时下单，无需 pandas 合并。",
    className: "qb-py-tip-zip",
  },
  {
    syntax: "concat( ) / merge( )",
    pattern: /\.(?:concat|merge)\s*\(/,
    en: "concat stacks tables vertically or horizontally; merge joins on keys like date and symbol. Used to blend price data with external factors or multiple signals.",
    zh: "concat 纵向或横向拼接表；merge 按日期、代码等键连接，用于合并价格与外部因子或多路信号。",
    className: "qb-py-tip-merge",
  },
  {
    syntax: "np.mean / np.std / np.log",
    pattern: /\bnp\.(?:mean|std|log|sum|max|min)\b/,
    en: "Core numpy aggregations across arrays—average signal, volatility scale, log returns. Faster than Python loops over thousands of stocks.",
    zh: "numpy 在数组上的聚合：均值、标准差、对数收益等，比用 Python 循环数千只股票更快。",
    className: "qb-py-tip-npagg",
  },
  {
    syntax: "np.where( )",
    pattern: /\bnp\.where\s*\(/,
    en: "Vectorized if/else on arrays—e.g. long when signal > 0 else flat. Keeps cross-sectional rules in one line without slow per-stock branching.",
    zh: "数组上的向量化条件选择（如信号>0 则做多否则空仓），一行完成截面规则而无需逐股分支。",
    className: "qb-py-tip-npwhere",
  },
  {
    syntax: "datetime / timedelta",
    pattern: /\b(?:datetime|timedelta)\b/,
    en: "Python date arithmetic—add months, skip weekends, or compare to publication dates. Often combined with self.Time to match calendar rules in papers.",
    zh: "Python 日期运算：加减月份、跳过周末或与发布日对齐，常与 self.Time 配合实现论文日历规则。",
    className: "qb-py-tip-datetime",
  },
  {
    syntax: "json.loads",
    pattern: /\bjson\.loads\b/,
    en: "Parses JSON text (from Download or API) into Python dicts/lists before building signals. Validate schema so missing fields do not crash the backtest.",
    zh: "把 JSON 文本（来自 Download 或 API）解析为字典/列表再建信号，应校验字段以免回测崩溃。",
    className: "qb-py-tip-json",
  },
  {
    syntax: "def OnEndOfDay",
    pattern: /\bdef\s+OnEndOf(?:Day|Algorithm)\b/,
    en: "Runs once at the end of each trading day (or at algorithm end). Useful for daily marks, logging, or forcing exits before the close.",
    zh: "每个交易日收盘（或算法结束）时运行一次，适合日终记账、日志或收盘前强制平仓。",
    className: "qb-py-tip-eod",
  },
  {
    syntax: "def OnOrderEvent",
    pattern: /\bdef\s+OnOrderEvent\b/,
    en: "Fires when order status changes—filled, partially filled, or canceled. Use for trade logging, bracket orders, or updating internal position trackers.",
    zh: "订单状态变化时触发（成交、部分成交、取消），用于交易记录、括号单或更新内部持仓跟踪。",
    className: "qb-py-tip-orderevent",
  },
  {
    syntax: "self.SetLeverage",
    pattern: /\bself\.SetLeverage\s*\(/,
    en: "Sets max leverage allowed on a security—2× means you can hold twice notional versus cash. Required for realistic futures, FX, or margin equity tests.",
    zh: "设定某标的最大杠杆（2× 表示名义敞口可达现金两倍），期货、外汇或融资股票回测常用。",
    className: "qb-py-tip-leverage",
  },
  {
    syntax: "StopMarketOrder / LimitIfTouched",
    pattern: /\b(?:StopMarket|StopLimit|LimitIfTouched|TrailingStop)Order\s*\(/,
    en: "Conditional orders that trigger when price hits a threshold—stops for risk control, limits for entries. More explicit than SetHoldings for event-driven rules.",
    zh: "价格触及条件才触发的订单——止损控风险、限价定入场，比 SetHoldings 更适合事件驱动规则。",
    className: "qb-py-tip-stoporder",
  },
  {
    syntax: "Insight / EmitInsights",
    pattern: /\b(?:Insight|EmitInsights)\b/,
    en: "Framework insights are typed predictions (up/down, magnitude, horizon) consumed by portfolio construction. Used in modular QC framework algorithms, not classic single-file scripts.",
    zh: "框架 Insight 是带方向、幅度、期限的预测，供组合构建模块使用，多见于 QC 模块化框架而非单文件脚本。",
    className: "qb-py-tip-insight",
  },
  {
    syntax: "ConstantAlphaModel",
    pattern: /\bConstantAlphaModel\b/,
    en: "A simple framework alpha that emits fixed-direction insights on a schedule—building block when prototyping pipeline-style algorithms.",
    zh: "框架中按固定节奏发出方向信号的简单 alpha，用于原型化流水线式算法。",
    className: "qb-py-tip-alpha",
  },
  {
    syntax: "statsmodels",
    pattern: /\bstatsmodels\b/,
    en: "Econometrics library for regressions, ARIMA, and statistical tests inside research code. Heavier than numpy alone; ensure imports are allowed in your QuantConnect project.",
    zh: "计量经济学库，用于回归、ARIMA 与检验。比纯 numpy 更重，需确认 QC 项目允许导入。",
    className: "qb-py-tip-stats",
  },
  {
    syntax: "lambda",
    pattern: /\blambda\s+\w+/,
    en: "Anonymous one-line function—often inside sorted() or map() to rank stocks by a signal value without defining a separate named function.",
    zh: "匿名单行函数，常见于 sorted/map 中按信号值排序股票，无需单独定义函数名。",
    className: "qb-py-tip-lambda",
  },
];
